(rule
 (deps
  (file ../en.tex))
 (target resume_en.pdf)
 (alias site)
 (action
  (progn (run lualatex ../en.tex) (run mv en.pdf %{target}))))

(rule
 (deps
  (file ../fr.tex))
 (target resume_fr.pdf)
 (alias site)
 (action
  (progn (run lualatex ../fr.tex) (run mv fr.pdf %{target}))))

(alias
 (name site)
 (deps (glob_files ./*.pdf)))