(rule
 (target resume_en.pdf)
 (alias site)
 (deps
  (file ../en.typ)
  (file emile.jpg)
  (glob_files ../fonts/*.otf))
 (action
  (run
   typst
   compile
   --ignore-system-fonts
   --font-path
   ../fonts
   ../en.typ
   %{target})))

(rule
 (target resume_fr.pdf)
 (alias site)
 (deps
  (file ../fr.typ)
  (file emile.jpg)
  (glob_files ../fonts/*.otf))
 (action
  (run
   typst
   compile
   --ignore-system-fonts
   --font-path
   ../fonts
   ../fr.typ
   %{target})))

(alias
 (name site)
 (deps
  (glob_files ./*.pdf)
  (glob_files ./*.html)))
