(rule
 (target style.css)
 (deps
  (file style.sass))
 (aliases style site)
 (action
  (run sass style.sass style.css)))

(rule
 (aliases site blog)
 (deps
  (source_tree ../blog))
 (targets
  (dir blog))
 (action
  (run blog_gen ../blog .)))

(rule
 (aliases site script)
 (action
  (copy ../src/jsoo/highlight.bc.js ./highlight.js)))

(rule
 (aliases site script)
 (action
  (copy ../src/jsoo/voronoi.bc.js ./voronoi.js)))

(copy_files
 (alias site)
 (files icons/*.svg))

(rule
 (targets fr.tex en.tex fr.typ en.typ resume.html index.html 404.html software.html)
 (alias site)
 (deps ../src/main.exe)
 (action
  (run ../src/main.exe)))
